# Generated by Django 4.1.6 on 2023-02-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="findUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("whatsapp_number", models.IntegerField(max_length=10)),
                ("instagram_url", models.URLField()),
                ("discord_username", models.CharField(max_length=30)),
            ],
        ),
    ]
